// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import * as dotenv from "dotenv";
import * as path from "path";
import { defineConfig } from "prisma/config";

// Load .env from project root (only in development, production uses env vars directly)
if (!process.env.DATABASE_URL) {
  dotenv.config({ path: path.resolve(__dirname, ".env") });
}

// DATABASE_URL may not be set during build (prisma generate), only required at runtime (migrate deploy)
const databaseUrl = process.env.DATABASE_URL || "postgresql://placeholder:placeholder@localhost:5432/placeholder";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
